In [118]:
import numpy as np

class Perceptron(object):
    """Impleents a perceptron network """
    
    def __init__(self,input_size,lr=1,epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
        
        
        
    def activation_fn(self,x):
        return 1 if x >= 0 else 0
    
    
    def predict(self,x):
        x = np.insert(x,0,1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    
    
    def fit(self,X,d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i],0,1)


In [119]:
X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
    ])

In [120]:
d = np.array([0,0,0,1])


In [121]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [122]:
d

array([0, 0, 0, 1])

In [123]:
perceptron = Perceptron(input_size=2)


In [124]:
perceptron.W

array([0., 0., 0.])

In [125]:
perceptron.fit(X,d)

In [126]:
perceptron.W

array([-3.,  2.,  1.])

In [127]:

print(perceptron.W)

[-3.  2.  1.]


In [129]:
perceptron.predict(np.asarray([0,0]))

0

In [130]:
mp = Perceptron(5)
x = np.asarray([1,1,0,0,0])
mp.predict(x)

1

In [131]:
mp.activation_fn(10)

1

In [132]:
mp.W

array([0., 0., 0., 0., 0., 0.])

 ## 1) Perceptron class tanımınında var olan fonksiyonları kısaca tanıtınız.
 
 ## __init__ fonksiyonu
Algılayıcıyı oluşturuyoruz. Ağırlık vektörünü oluşturmak için girdi alıyoruz. 
Girdi boyutunu ise bir arttırıyoruz ki sapmayı dahil edebilelim.
öğrenme oranını ve devir sayısınıda kendimiz fonksiyona ekledik dışarıdan parametre olarak değiştirilebilirler.

## activation_fn fonksiyonu
Aktivasyon fonksiyonumuz eşik değeri belirliyoruz, eğer girdi 0 dan büyük veya eşitse 1 değilse 0 döndürüyoruz. Böylelikle gelen input için çıkacak output'u bulmuş oluyoruz.

## predict fonksiyonu
Algılayıcı aracılığıyla girdiyi çalıştırmak ve çıktı döndürmek için yazılan fonksiyon. 
Tahmin fonksiyonudur. 
Eğilimi giriş vektörüne ekliyoruz ardından iç çarpımı hesaplıyor ve aktivasyon fonksiyonunu kullanıyoruz. Makineyi eğittikten sonra input'un sonucunu tahmin ediyor.

## fit fonksiyonu
Tüm eğitim setini yineliyoruz ve ağırlığı devir sayımız kadar güncelliyoruz.
Ağırlığı güncellerken ise sapmayı girdiye ekliyoruz.
ardından ise tahminizi oluşturabiliyoruz, hatamızı hesaplayabiliyoruz, ve güncelleme kuralımızı uyguluyoruz. Bu işlemler sonucu makineyi eğittimiz fonksiyondur.

## 2) XOR için verileri değiştirip çalışmasınızı gözlemleyiniz.
## Gözlemimim en sonda predict yapıldıktan sonraki sonuçlardan sonradır.

##  XOR İŞLEMİ SONUCU VE GÖZLEMİM

X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
    ])

d = np.array([0,1,1,0])

print(X) - >> array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])
       

print(d) ->> array([0, 1, 1, 0])


perceptron = Perceptron(input_size=2)

perceptron.W ->> array([0., 0., 0.])

perceptron.fit(X,d)

perceptron.W --> array([ 0., -1.,  0.])

print(perceptron.W) ->> [ 0. -1.  0.]

## burada birden fazla perceptron.predict(np.asarray([x,y]) denemesi sonuçları yer almaktadır

perceptron.predict(np.asarray([0,0])) --> 1

perceptron.predict(np.asarray([1,0])) --> 0

perceptron.predict(np.asarray([0,1])) --> 1

perceptron.predict(np.asarray([1,1])) --> 0

## Gözlem:
Bu sonuçlardan anlaşıldığı üzere XOR işlemi yapıldığında predict sonuçlarımız doğru outputları vermedi. Bunun sebebi ise Algılayıcıların sınırlamasından kaynaklanmaktadır, yalnızca doğrusal ayrılabilen sorunları çözebilmektedirler. XOR ise doğrusal olarak ayrılamadığından tek katmanlı algılayıcıları xor kapısı için kullanamayız.

## 3) bu class ile dersimize kayıtlı 40 öğrenci için imza tanıması yapılırsa X ve d değerlerini ne olur, predict fonksiyonu nasıl kullanılır açıklayınız

X değerleri input ve d değerleri ise output'u temsil etmekte. Biz bunları kullanarak makineyi eğitmekteyiz. Bunun sonucunda X değeri 40 adet dizi tutar bu diziler ise öğrencilerin imzalarını tutmaktadır. d ise 40 elemanlıdır her biri X dizisindeki imzaların öğrenci karşılığıdır.

### yani buradan

X = [[img_1.reshape(m*n*3,1)],[img_2.reshape(m*n*3,1)].....,[img_40.reshape(m*n*3,1)]]
d = ["ahmet","mehmet",......"veli"] şeklinde 40 adet farklı veri olacaktır her imzanın öğrenci output'u olacak şekilde.



Predict fonksiyonunu ise bir öğrencinin imzası yani input alınır predict fonksiyonuna gönderilir. Ardından gerekli işlemler yapılıp output verilir ve hangi öğrenciye ait imza olduğu ortaya çıkar.


## 4)Bu modelin hatası nasıl elde edilir, kendi çözümünüzü/ yorumunuzu yazınız.

Bir fonksiyon ile Accuracy oluştururdum bunu ise doğru olanlar/toplam deneme sayısını bölerek elde ederdim. Burdan gelen sonuç ise 0-1 arasında olurdu ve buda doğruluk oranını verir. Bu oranı ise 1 den çıkarttığımızda hata oranını buluruz.

Yukarıda ki tanım sonucunda oluşacak örnek fonksiyon bu şekildedir. Fonksiyona predict edilecek dizi elemanları gönderilir bunlar ise predict fonksiyonuna gönderilir ardından output'u elde ederiz. Bu output ise doğrumu değilmi onun kontrolü yapılır datasetimizdeki d dizisi ile. Doğruysa count 1 artar değilse artmaz. Tüm işlemler sonucu başarı oranı bulunur. 1'den başarı oranı çıkar ise hata oranı elde edilir.

# Kod kısmı
def accuracy(predict_edilecekler_dizisi,X,d):
    count=0
    for i in predict_edilecekler_dizisi:
       kontrol = predict(i)
       for j in range(len(X)):
           if(X[j]==i):
               if(kontrol==d[j]):
                   count+=1
   print("başarı oranı", accuracy/len(predict_edilecekler_dizisi)
   print("hata oranı" , 1-(accuracy/len(predict_edilecekler_dizisi))